"""A new graph version cannot turn extracted prose into declared authority.

These pins cover strict proposal extraction and historical-origin consumer
checks, not human authentication. Local Graph creation remains privileged.
"""

import pytest

from causal_continuity_engine.engine import Engine
from tests.test_api_contract import LocalAPI
from tests.test_engine_e2e import PRJ, REPOSITORY_ID, _issue

CASES = [
    ("requirement", "The exporter must stream rows instead of buffering."),
    ("constraint", "The exporter must never disclose the private report."),
    ("decision", "We decided to keep the report entirely local."),
    ("task", "- [ ] inspect the generated report before delivery"),
]


def _visible_ids(packet):
    return {
        item["node_id"]
        for items in (
            packet["authority"]["active_requirements"],
            packet["authority"]["active_constraints"],
            packet["accepted_decisions"],
            packet["open_work"]["tasks"],
            packet["mission"]["pinned_control_state"],
        )
        for item in items
    }


@pytest.fixture
def engine(tmp_path):
    instance = Engine(tmp_path / "origin.db", tenant_id="ten_origin", workdir=tmp_path)
    instance.create_project(
        "origin", project_id=PRJ, repository_id=REPOSITORY_ID,
        repository="octo/demo")
    try:
        yield instance
    finally:
        instance.close()


def _extracted(engine, kind, text):
    engine.ingest_github(PRJ, "issues", "origin-1", _issue(1, text))
    node, = engine.graph.current(PRJ, "claim")
    assert node["extractor"] and node["event_id"]
    assert node["data"]["proposed_kind"] == kind
    assert node["data"]["needs_confirmation"] is True
    assert not engine.graph.may_mandate(node)
    assert engine.memory.tier_of(PRJ, node.id) is None
    before = tuple(engine.store._conn.iterdump())
    with pytest.raises(ValueError, match="authority"):
        engine.memory.promote(PRJ, node.id, "L0", actor="owner")
    assert tuple(engine.store._conn.iterdump()) == before
    assert node.id not in _visible_ids(engine.resume_packet(PRJ))
    # Privileged fixture only: plant a pre-boundary assignment to exercise
    # stale-assignment reads. This is not a supported promotion or approval.
    engine.memory._record(PRJ, node.id, "L0", "promote", "legacy-fixture",
                          "retained historical assignment")
    assert engine.memory.tier_of(PRJ, node.id) == "L0"
    assert engine.memory.l0(PRJ) == []
    engine.policy.set_project_config(PRJ, {"prose_may_mandate": False}, actor="owner")
    assert node.id not in _visible_ids(engine.resume_packet(PRJ))
    return node


@pytest.mark.parametrize("kind,text", CASES)
def test_versioned_proposal_stays_excluded_after_local_edit(engine, kind, text):
    original = _extracted(engine, kind, text)
    updated = engine.graph.put_node(
        entity_type=original["entity_type"], tenant_id=engine.tenant_id, project_id=PRJ,
        node_id=original.id, data={"review_note": "reviewed"})
    # Provenance belongs to a particular version. Do not pretend the later
    # local edit was generated by the original extractor or source event.
    assert updated["event_id"] is None and updated["extractor"] is None
    assert not engine.graph.may_mandate(updated)
    with pytest.raises(ValueError, match="authority"):
        engine.memory.promote(PRJ, original.id, "L0", actor="owner")
    assert engine.graph.history(original.id)[0] == {
        **original, "tx_to": engine.graph.history(original.id)[0]["tx_to"]}

    packet = engine.resume_packet(PRJ)

    assert original.id not in _visible_ids(packet)
    assert any(item["reason"] == "authority_unavailable" for item in packet["omissions"])
    assert engine.memory.tier_of(PRJ, original.id) == "L0"  # assignment history is not erased


@pytest.mark.parametrize("kind,text", CASES[:3])
@pytest.mark.parametrize("patch", [None, {"needs_confirmation": False, "source_ref": ""}])
def test_http_resolution_cannot_erase_prose_origin(engine, kind, text, patch):
    original = _extracted(engine, kind, text)
    request = {"action": "narrow"}
    if patch is not None:
        request["data"] = patch
    before = tuple(engine.store._conn.iterdump())
    api = LocalAPI(engine, project_id=PRJ)
    try:
        status, body, _ = api.request(
            "POST", f"/v1/assumptions/{original.id}:resolve", request)
    finally:
        api.close()
    updated = engine.graph.get(original.id)
    if patch is None:
        assert status == 200, body
        assert updated["extractor"] is None and updated["event_id"] is None
        assert updated["status"] == "active"
        assert updated["authority"] == original["authority"]
        assert updated["data"] == original["data"]
    else:
        assert status == 400, body
        assert body["error"]["code"] == "invalid_request"
        assert body["error"]["field"] == "data"
        assert updated == original
        assert tuple(engine.store._conn.iterdump()) == before
    assert not engine.graph.may_mandate(updated)

    packet = engine.resume_packet(PRJ)

    assert original.id not in _visible_ids(packet)
    assert any(item["reason"] == "authority_unavailable" for item in packet["omissions"])


@pytest.mark.parametrize("kind,text", CASES)
def test_direct_local_graph_control_is_not_reclassified_as_prose(engine, kind, text):
    engine.policy.set_project_config(PRJ, {"prose_may_mandate": False}, actor="owner")
    node = engine.graph.put_node(
        entity_type=kind, tenant_id=engine.tenant_id, project_id=PRJ,
        data={"statement": text},
        status="open" if kind == "task" else "active", authority="human_decision")
    engine.memory.promote(PRJ, node.id, "L0", actor="owner")
    engine.graph.put_node(
        entity_type=kind, tenant_id=engine.tenant_id, project_id=PRJ,
        node_id=node.id, data={"review_note": "reviewed"})

    assert node.id in _visible_ids(engine.resume_packet(PRJ))


def test_origin_survives_multiple_versions_and_reopen(engine):
    original = _extracted(engine, *CASES[0])
    for index in range(3):
        engine.graph.put_node(
            entity_type=original["entity_type"], tenant_id=engine.tenant_id,
            project_id=PRJ, node_id=original.id, data={"revision": index})
    # A separate Engine must derive the same answer from persisted history,
    # without relying on a cache populated by the original producer.
    reopened = Engine(engine.store.path, tenant_id=engine.tenant_id)
    try:
        assert original.id not in _visible_ids(reopened.resume_packet(PRJ))
    finally:
        reopened.close()


def test_permissive_policy_is_refused_without_reauthorizing_historical_prose(engine):
    original = _extracted(engine, *CASES[0])
    engine.graph.put_node(
        entity_type=original["entity_type"], tenant_id=engine.tenant_id,
        project_id=PRJ, node_id=original.id, data={"review_note": "reviewed"})
    before = tuple(engine.store._conn.iterdump())
    with pytest.raises(ValueError, match="prose_may_mandate"):
        engine.policy.set_project_config(PRJ, {"prose_may_mandate": True}, actor="owner")
    assert tuple(engine.store._conn.iterdump()) == before
    assert engine.policy.project_config(PRJ)["prose_may_mandate"] is False

    assert original.id not in _visible_ids(engine.resume_packet(PRJ))


def test_prior_composition_basis_cannot_keep_its_watermark_current(engine, monkeypatch):
    _extracted(engine, *CASES[0])
    current_basis = engine._packet_control_basis

    def prior_basis(project_id):
        # Version-domain simulation, not a claim to run the old composer:
        # all state is unchanged; only the prior basis identity is restored.
        return {**current_basis(project_id), "schema_version": "cce.packet-control-basis.v1"}

    with monkeypatch.context() as patch:
        patch.setattr(engine, "_packet_control_basis", prior_basis)
        prior = engine.resume_packet(PRJ)
        assert not engine.packet_is_stale(PRJ)

    assert engine.packet_is_stale(PRJ)
    current = engine.resume_packet(PRJ)
    assert current["project_state_basis"] != prior["project_state_basis"]
    assert not engine.packet_is_stale(PRJ)
